verbose: false

image:
  repository: "developdockerstate/datacollector"
  tag: "latest"
  pullPolicy: IfNotPresent

datainjestor:
  uri: http://localtest

fanniemae:
  latest:
    enabled: false
    schedule: "*/1 * * * *"
  history:
    enabled: false
    startyear: 0
    endyear: 0

  uri: https://local
  secret: 
    name: fanniemae-secret
    key:
      username: username
      password: password
  
  restartPolicy: OnFailure
