{{ if .Values.hemnet.forsale.latest.enabled }}
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: hemnet-forsale-latest
  namespace: {{ .Release.Namespace }}
  labels:
    app: hemnet-forsale-latest
spec:
  schedule: {{ .Values.hemnet.forsale.latest.schedule }}
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hemnet-forsale-latest-job
            image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
            imagePullPolicy: {{ .Values.image.pullPolicy }}
            args: 
              - hemnet-latest-for-sale-properties
            env:
              - name: COLLECTOR_CONFIG_PATH
                value: /etc/collector/config.ini
              - name: COLLECTOR_VERBOSE
                value: {{ .Values.verbose | quote }}
            # readinessProbe:
            #   ... handle readiness checks
            # livenessProbe:
            #   ... handle liveness checks
            volumeMounts:
              - name: config
                mountPath: /etc/collector
          restartPolicy: {{ .Values.hemnet.restartPolicy }}
          volumes:
          - name: config
            configMap:
              name: hemnet-config
{{ end }}
