

redis:
  image:
    repository: redis
    tag: alpine3.14
    pullPolicy: IfNotPresent

  containerPort: 6379
  restartPolicy: Always
  workingdir: /etc/redis/data

rediscmd:
  replicaCount: 1
  image:
    repository: rediscommander/redis-commander
    tag: latest
    pullPolicy: IfNotPresent
  containerPort: 8080