apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-data-pvc
  namespace: {{ .Release.Namespace }}
  labels:
    app: redis-data-pvc
spec:
  accessModes:
    - ReadWriteOnce # Only needed for redis instance
  resources:
    requests:
      storage: 8Gi