apiVersion: v1
kind: Service
metadata:
  name: redis-server
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: redis-server
  ports:
    - protocol: TCP
      port: 16379
      targetPort: {{ .Values.redis.containerPort }}
