apiVersion: v1
kind: ConfigMap
metadata:
  name: fanniemae-sf-config
  namespace: {{ .Release.Namespace }}
data:
  config.ini: |-
    [Collector]
    Identifier=fanniemae-sf-job
    InjestorApiUri={{ .Values.datainjestor.uri }}
    UserAgent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.121 Safari/537.36"

    [RateLimiter]
    TimeIntervalSeconds=60
    MaxActions=5

    [FannieMae]
    Uri={{ .Values.fanniemae.uri }}
  
{{ if and .Values.fanniemae.history.startyear .Values.fanniemae.history.endyear }}
    StartYear={{ .Values.fanniemae.history.startyear}}
    EndYear={{ .Values.fanniemae.history.endyear}}
{{ end }}